"""
Invoice Module - Handle invoice generation, list, and details
"""

from flask import Blueprint, request, jsonify, session, render_template_string
from datetime import datetime, timedelta
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from common import Database, dict_to_sql_insert
from config import Config

invoice_bp = Blueprint('invoice', __name__, url_prefix='/api/invoice')


# ============================================
# GENERATE INVOICE
# ============================================

@invoice_bp.route('/generate/<int:order_id>', methods=['POST'])
def generate_invoice(order_id):
    """Generate invoice for an order"""
    try:
        # Check if user is logged in
        if 'user_id' not in session:
            return jsonify({'error': 'Unauthorized'}), 401
        
        # Check if invoice already exists
        existing_invoice = Database.execute_query(
            "SELECT id, invoice_number FROM invoices WHERE order_id = %s",
            (order_id,),
            fetch_one=True
        )
        
        if existing_invoice:
            return jsonify({
                'message': 'Invoice already exists',
                'invoice_id': existing_invoice['id'],
                'invoice_number': existing_invoice['invoice_number']
            }), 200
        
        # Get order details
        order = Database.execute_query(
            "SELECT id, user_id, total_amount, status FROM orders WHERE id = %s",
            (order_id,),
            fetch_one=True
        )
        
        if not order:
            return jsonify({'error': 'Order not found'}), 404
        
        # Check permission
        user_type = session.get('user_type')
        if user_type == 'user' and order['user_id'] != session['user_id']:
            return jsonify({'error': 'Unauthorized'}), 403
        
        # Calculate invoice amounts
        subtotal = order['total_amount']
        tax_amount = subtotal * Config.TAX_RATE
        total_amount = subtotal + tax_amount
        
        # Create invoice
        invoice_data = {
            'order_id': order_id,
            'invoice_number': '',  # Will be auto-generated by trigger
            'user_id': order['user_id'],
            'subtotal': subtotal,
            'tax_amount': tax_amount,
            'discount_amount': 0.00,
            'total_amount': total_amount,
            'due_date': datetime.now() + timedelta(days=30)
        }
        
        query, values = dict_to_sql_insert('invoices', invoice_data)
        invoice_id = Database.execute_query(query, values)
        
        # Get invoice number
        invoice = Database.execute_query(
            "SELECT invoice_number FROM invoices WHERE id = %s",
            (invoice_id,),
            fetch_one=True
        )
        
        return jsonify({
            'message': 'Invoice generated successfully',
            'invoice_id': invoice_id,
            'invoice_number': invoice['invoice_number']
        }), 201
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ============================================
# INVOICE LIST
# ============================================

@invoice_bp.route('/my-invoices', methods=['GET'])
def get_my_invoices():
    """Get current user's invoices"""
    try:
        # Check if user is logged in
        if 'user_id' not in session or session.get('user_type') != 'user':
            return jsonify({'error': 'Unauthorized'}), 401
        
        user_id = session['user_id']
        
        invoices = Database.execute_query(
            """SELECT 
                i.id, i.invoice_number, i.total_amount, i.invoice_date,
                o.order_number, o.status as order_status
            FROM invoices i
            JOIN orders o ON i.order_id = o.id
            WHERE i.user_id = %s
            ORDER BY i.invoice_date DESC""",
            (user_id,),
            fetch_all=True
        )
        
        return jsonify({'invoices': invoices}), 200
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@invoice_bp.route('/all', methods=['GET'])
def get_all_invoices():
    """Get all invoices (admin only)"""
    try:
        # Check if admin is logged in
        if session.get('user_type') != 'admin':
            return jsonify({'error': 'Unauthorized. Admin access required'}), 403
        
        invoices = Database.execute_query(
            """SELECT 
                i.id, i.invoice_number, i.total_amount, i.invoice_date,
                o.order_number, o.status as order_status,
                u.full_name as customer_name, u.email as customer_email
            FROM invoices i
            JOIN orders o ON i.order_id = o.id
            JOIN users u ON i.user_id = u.id
            ORDER BY i.invoice_date DESC""",
            fetch_all=True
        )
        
        return jsonify({'invoices': invoices}), 200
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ============================================
# SINGLE INVOICE DETAILS
# ============================================

@invoice_bp.route('/<int:invoice_id>', methods=['GET'])
def get_invoice_details(invoice_id):
    """Get detailed invoice information"""
    try:
        # Check if user is logged in
        if 'user_id' not in session:
            return jsonify({'error': 'Unauthorized'}), 401
        
        # Get invoice
        invoice = Database.execute_query(
            """SELECT 
                i.id, i.invoice_number, i.subtotal, i.tax_amount,
                i.discount_amount, i.total_amount, i.invoice_date, i.due_date,
                i.notes,
                o.id as order_id, o.order_number, o.status as order_status,
                o.payment_method, o.payment_status, o.delivery_address,
                o.created_at as order_date,
                u.id as user_id, u.full_name as customer_name,
                u.email as customer_email, u.phone as customer_phone,
                u.address as customer_address
            FROM invoices i
            JOIN orders o ON i.order_id = o.id
            JOIN users u ON i.user_id = u.id
            WHERE i.id = %s""",
            (invoice_id,),
            fetch_one=True
        )
        
        if not invoice:
            return jsonify({'error': 'Invoice not found'}), 404
        
        # Check permission
        user_type = session.get('user_type')
        if user_type == 'user' and invoice['user_id'] != session['user_id']:
            return jsonify({'error': 'Unauthorized'}), 403
        
        # Get order items
        items = Database.execute_query(
            """SELECT 
                oi.quantity, oi.price, oi.subtotal,
                m.name as item_name, m.description as item_description
            FROM order_items oi
            JOIN menu_items m ON oi.menu_item_id = m.id
            WHERE oi.order_id = %s""",
            (invoice['order_id'],),
            fetch_all=True
        )
        
        return jsonify({
            'invoice': invoice,
            'items': items
        }), 200

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# ============================================
# PRINT INVOICE (HTML Template)
# ============================================

@invoice_bp.route('/print/<int:invoice_id>', methods=['GET'])
def print_invoice(invoice_id):
    """Get printable HTML invoice"""
    try:
        # Check if user is logged in
        if 'user_id' not in session:
            return jsonify({'error': 'Unauthorized'}), 401

        # Get invoice details (reuse the same query)
        invoice = Database.execute_query(
            """SELECT
                i.id, i.invoice_number, i.subtotal, i.tax_amount,
                i.discount_amount, i.total_amount, i.invoice_date, i.due_date,
                i.notes,
                o.id as order_id, o.order_number, o.status as order_status,
                o.payment_method, o.payment_status, o.delivery_address,
                o.created_at as order_date,
                u.id as user_id, u.full_name as customer_name,
                u.email as customer_email, u.phone as customer_phone,
                u.address as customer_address
            FROM invoices i
            JOIN orders o ON i.order_id = o.id
            JOIN users u ON i.user_id = u.id
            WHERE i.id = %s""",
            (invoice_id,),
            fetch_one=True
        )

        if not invoice:
            return jsonify({'error': 'Invoice not found'}), 404

        # Check permission
        user_type = session.get('user_type')
        if user_type == 'user' and invoice['user_id'] != session['user_id']:
            return jsonify({'error': 'Unauthorized'}), 403

        # Get order items
        items = Database.execute_query(
            """SELECT
                oi.quantity, oi.price, oi.subtotal,
                m.name as item_name, m.description as item_description
            FROM order_items oi
            JOIN menu_items m ON oi.menu_item_id = m.id
            WHERE oi.order_id = %s""",
            (invoice['order_id'],),
            fetch_all=True
        )

        # HTML template for invoice
        html_template = """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Invoice {{ invoice_number }}</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .invoice-header { text-align: center; margin-bottom: 30px; }
                .invoice-header h1 { color: #333; margin: 0; }
                .invoice-info { display: flex; justify-content: space-between; margin-bottom: 30px; }
                .company-info, .customer-info { width: 45%; }
                .company-info h3, .customer-info h3 { margin-top: 0; color: #666; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
                th { background-color: #f8f9fa; font-weight: bold; }
                .text-right { text-align: right; }
                .totals { margin-left: auto; width: 300px; }
                .totals table { margin-bottom: 0; }
                .total-row { font-weight: bold; font-size: 1.2em; }
                .footer { margin-top: 50px; text-align: center; color: #666; font-size: 0.9em; }
                @media print {
                    body { margin: 20px; }
                    .no-print { display: none; }
                }
            </style>
        </head>
        <body>
            <div class="invoice-header">
                <h1>🍔 Food Ordering System</h1>
                <p>Invoice</p>
            </div>

            <div class="invoice-info">
                <div class="company-info">
                    <h3>From:</h3>
                    <p><strong>Food Ordering System</strong><br>
                    123 Restaurant Street<br>
                    City, State 12345<br>
                    Phone: (123) 456-7890<br>
                    Email: info@foodorder.com</p>
                </div>

                <div class="customer-info">
                    <h3>Bill To:</h3>
                    <p><strong>{{ customer_name }}</strong><br>
                    {{ customer_address }}<br>
                    Phone: {{ customer_phone }}<br>
                    Email: {{ customer_email }}</p>
                </div>
            </div>

            <table>
                <tr>
                    <td><strong>Invoice Number:</strong> {{ invoice_number }}</td>
                    <td><strong>Order Number:</strong> {{ order_number }}</td>
                </tr>
                <tr>
                    <td><strong>Invoice Date:</strong> {{ invoice_date }}</td>
                    <td><strong>Order Date:</strong> {{ order_date }}</td>
                </tr>
                <tr>
                    <td><strong>Payment Method:</strong> {{ payment_method }}</td>
                    <td><strong>Payment Status:</strong> {{ payment_status }}</td>
                </tr>
            </table>

            <h3>Order Items</h3>
            <table>
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Description</th>
                        <th class="text-right">Price</th>
                        <th class="text-right">Quantity</th>
                        <th class="text-right">Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ item.item_name }}</td>
                        <td>{{ item.item_description }}</td>
                        <td class="text-right">${{ "%.2f"|format(item.price) }}</td>
                        <td class="text-right">{{ item.quantity }}</td>
                        <td class="text-right">${{ "%.2f"|format(item.subtotal) }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="totals">
                <table>
                    <tr>
                        <td>Subtotal:</td>
                        <td class="text-right">${{ "%.2f"|format(subtotal) }}</td>
                    </tr>
                    <tr>
                        <td>Tax ({{ tax_rate }}%):</td>
                        <td class="text-right">${{ "%.2f"|format(tax_amount) }}</td>
                    </tr>
                    {% if discount_amount > 0 %}
                    <tr>
                        <td>Discount:</td>
                        <td class="text-right">-${{ "%.2f"|format(discount_amount) }}</td>
                    </tr>
                    {% endif %}
                    <tr class="total-row">
                        <td>Total:</td>
                        <td class="text-right">${{ "%.2f"|format(total_amount) }}</td>
                    </tr>
                </table>
            </div>

            <div class="footer">
                <p>Thank you for your order!</p>
                <p>This is a computer-generated invoice.</p>
                <button class="no-print" onclick="window.print()">Print Invoice</button>
            </div>
        </body>
        </html>
        """

        # Render template (simplified - in production use Jinja2)
        html = html_template
        html = html.replace('{{ invoice_number }}', invoice['invoice_number'])
        html = html.replace('{{ order_number }}', invoice['order_number'])
        html = html.replace('{{ customer_name }}', invoice['customer_name'])
        html = html.replace('{{ customer_address }}', invoice['customer_address'] or 'N/A')
        html = html.replace('{{ customer_phone }}', invoice['customer_phone'] or 'N/A')
        html = html.replace('{{ customer_email }}', invoice['customer_email'])
        html = html.replace('{{ invoice_date }}', str(invoice['invoice_date']))
        html = html.replace('{{ order_date }}', str(invoice['order_date']))
        html = html.replace('{{ payment_method }}', invoice['payment_method'].upper())
        html = html.replace('{{ payment_status }}', invoice['payment_status'].upper())
        html = html.replace('{{ tax_rate }}', str(int(Config.TAX_RATE * 100)))

        # Build items HTML
        items_html = ''
        for item in items:
            items_html += f"""
                    <tr>
                        <td>{item['item_name']}</td>
                        <td>{item['item_description']}</td>
                        <td class="text-right">${item['price']:.2f}</td>
                        <td class="text-right">{item['quantity']}</td>
                        <td class="text-right">${item['subtotal']:.2f}</td>
                    </tr>
            """

        html = html.replace('{% for item in items %}', '').replace('{% endfor %}', '')
        html = html.replace('{{ item.item_name }}', '').replace('{{ item.item_description }}', '')
        html = html.replace('{{ "%.2f"|format(item.price) }}', '').replace('{{ item.quantity }}', '')
        html = html.replace('{{ "%.2f"|format(item.subtotal) }}', '')

        # Insert items
        html = html.replace('</tbody>', items_html + '</tbody>')

        # Replace amounts
        html = html.replace('{{ "%.2f"|format(subtotal) }}', f"{invoice['subtotal']:.2f}")
        html = html.replace('{{ "%.2f"|format(tax_amount) }}', f"{invoice['tax_amount']:.2f}")
        html = html.replace('{{ "%.2f"|format(discount_amount) }}', f"{invoice['discount_amount']:.2f}")
        html = html.replace('{{ "%.2f"|format(total_amount) }}', f"{invoice['total_amount']:.2f}")

        # Handle discount conditional
        if invoice['discount_amount'] <= 0:
            html = html.replace('{% if discount_amount > 0 %}', '<!--')
            html = html.replace('{% endif %}', '-->')
        else:
            html = html.replace('{% if discount_amount > 0 %}', '')
            html = html.replace('{% endif %}', '')

        return html, 200, {'Content-Type': 'text/html'}

    except Exception as e:
        return jsonify({'error': str(e)}), 500

